# Generated by Django 6.0.2 on 2026-02-28 12:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('ticker', models.CharField(max_length=10, unique=True)),
                ('sector', models.CharField(blank=True, max_length=50, null=True)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnnualReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('report_date', models.DateField()),
                ('revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('cost_of_sales', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('gross_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('operating_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('net_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('eps', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_assets', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('total_liabilities', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('equity', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('current_assets', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('current_liabilities', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('operating_cashflow', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('investing_cashflow', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('financing_cashflow', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('net_cashflow', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fins.company')),
            ],
            options={
                'ordering': ['-year'],
                'unique_together': {('company', 'year')},
            },
        ),
        migrations.CreateModel(
            name='QuarterReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('quarter', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('report_date', models.DateField()),
                ('revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('cost_of_sales', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('gross_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('operating_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('net_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('eps', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_assets', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('total_liabilities', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('equity', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('current_assets', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('current_liabilities', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('operating_cashflow', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('investing_cashflow', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('financing_cashflow', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('net_cashflow', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fins.company')),
            ],
            options={
                'ordering': ['-year', '-quarter'],
                'unique_together': {('company', 'year', 'quarter')},
            },
        ),
    ]
