# Generated by Django 6.0.2 on 2026-02-28 15:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('ticker', models.CharField(max_length=10, unique=True)),
                ('sector', models.CharField(blank=True, max_length=50, null=True)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnnualReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('report_date', models.DateField()),
                ('revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('cost_of_sales', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('gross_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('operating_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('net_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('eps', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_assets', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('total_liabilities', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('equity', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('current_assets', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('current_liabilities', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('operating_cashflow', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('investing_cashflow', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('financing_cashflow', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('net_cashflow', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fins.company')),
            ],
            options={
                'ordering': ['-year'],
                'indexes': [models.Index(fields=['company'], name='fins_annual_company_316c71_idx'), models.Index(fields=['year'], name='fins_annual_year_05a55d_idx')],
                'unique_together': {('company', 'year')},
            },
        ),
        migrations.CreateModel(
            name='QuarterReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('quarter', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('report_date', models.DateField()),
                ('revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('cost_of_sales', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('gross_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('operating_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('net_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('eps', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_assets', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('total_liabilities', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('equity', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('current_assets', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('current_liabilities', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('operating_cashflow', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('investing_cashflow', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('financing_cashflow', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('net_cashflow', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fins.company')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-company', '-year', '-quarter'],
                'indexes': [models.Index(fields=['company'], name='fins_quarte_company_9856a5_idx'), models.Index(fields=['year'], name='fins_quarte_year_62bc87_idx'), models.Index(fields=['quarter'], name='fins_quarte_quarter_aa0db1_idx')],
                'unique_together': {('company', 'year', 'quarter')},
            },
        ),
    ]
